# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Builds

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  building:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: ['gcc', 'clang']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install oniontrace dependencies
        run: sudo apt-get install -y ${{ matrix.cc }} cmake libglib2.0-0 libglib2.0-dev

      - name: Build oniontrace
        run: |
          mkdir -p build
          cd build
          CC=${{ matrix.cc }} cmake ..
          make

      - name: Install oniontracetools dependencies
        run: sudo apt-get install -y python3 python3-dev python3-pip python3-venv libxml2 libxml2-dev libxslt1.1 libxslt1-dev libpng16-16 libpng-dev libfreetype6 libfreetype6-dev libblas-dev liblapack-dev

      - name: Build oniontracetools
        run: |
          python3 -m venv build/toolsenv
          source build/toolsenv/bin/activate
          pip install -r tools/requirements.txt
          pip install -I tools/
